/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedMediaIndexRouteImport } from './routes/_authenticated/media/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCatalogAttributesRouteRouteImport } from './routes/_authenticated/catalog/attributes/route'
import { Route as AuthenticatedUserUsersIndexRouteImport } from './routes/_authenticated/user/users/index'
import { Route as AuthenticatedShippingZonesIndexRouteImport } from './routes/_authenticated/shipping/zones/index'
import { Route as AuthenticatedShippingShipmentsIndexRouteImport } from './routes/_authenticated/shipping/shipments/index'
import { Route as AuthenticatedShippingRatesIndexRouteImport } from './routes/_authenticated/shipping/rates/index'
import { Route as AuthenticatedShippingMethodsIndexRouteImport } from './routes/_authenticated/shipping/methods/index'
import { Route as AuthenticatedSettingSettingsIndexRouteImport } from './routes/_authenticated/setting/settings/index'
import { Route as AuthenticatedOrderOrdersIndexRouteImport } from './routes/_authenticated/order/orders/index'
import { Route as AuthenticatedContentPagesIndexRouteImport } from './routes/_authenticated/content/pages/index'
import { Route as AuthenticatedCatalogProductsIndexRouteImport } from './routes/_authenticated/catalog/products/index'
import { Route as AuthenticatedCatalogProductCommentsIndexRouteImport } from './routes/_authenticated/catalog/product-comments/index'
import { Route as AuthenticatedCatalogOptionsIndexRouteImport } from './routes/_authenticated/catalog/options/index'
import { Route as AuthenticatedCatalogCategoriesIndexRouteImport } from './routes/_authenticated/catalog/categories/index'
import { Route as AuthenticatedCatalogAttributesIndexRouteImport } from './routes/_authenticated/catalog/attributes/index'
import { Route as AuthenticatedContentPagesCreateRouteImport } from './routes/_authenticated/content/pages/create'
import { Route as AuthenticatedCatalogProductsCreateRouteImport } from './routes/_authenticated/catalog/products/create'
import { Route as AuthenticatedCatalogAttributesTemplatesRouteImport } from './routes/_authenticated/catalog/attributes/templates'
import { Route as AuthenticatedCatalogAttributesGroupsRouteImport } from './routes/_authenticated/catalog/attributes/groups'
import { Route as AuthenticatedCatalogOptionValuesIdIndexRouteImport } from './routes/_authenticated/catalog/option-values/$id/index'
import { Route as AuthenticatedOrderOrdersIdShowRouteImport } from './routes/_authenticated/order/orders/$id/show'
import { Route as AuthenticatedContentPagesIdEditRouteImport } from './routes/_authenticated/content/pages/$id/edit'
import { Route as AuthenticatedCatalogProductsIdEditRouteImport } from './routes/_authenticated/catalog/products/$id/edit'
import { Route as AuthenticatedCatalogAttributesValuesIdIndexRouteImport } from './routes/_authenticated/catalog/attributes/values/$id/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedMediaIndexRoute = AuthenticatedMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogAttributesRouteRoute =
  AuthenticatedCatalogAttributesRouteRouteImport.update({
    id: '/catalog/attributes',
    path: '/catalog/attributes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserUsersIndexRoute =
  AuthenticatedUserUsersIndexRouteImport.update({
    id: '/user/users/',
    path: '/user/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShippingZonesIndexRoute =
  AuthenticatedShippingZonesIndexRouteImport.update({
    id: '/shipping/zones/',
    path: '/shipping/zones/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShippingShipmentsIndexRoute =
  AuthenticatedShippingShipmentsIndexRouteImport.update({
    id: '/shipping/shipments/',
    path: '/shipping/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShippingRatesIndexRoute =
  AuthenticatedShippingRatesIndexRouteImport.update({
    id: '/shipping/rates/',
    path: '/shipping/rates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShippingMethodsIndexRoute =
  AuthenticatedShippingMethodsIndexRouteImport.update({
    id: '/shipping/methods/',
    path: '/shipping/methods/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingSettingsIndexRoute =
  AuthenticatedSettingSettingsIndexRouteImport.update({
    id: '/setting/settings/',
    path: '/setting/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderOrdersIndexRoute =
  AuthenticatedOrderOrdersIndexRouteImport.update({
    id: '/order/orders/',
    path: '/order/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentPagesIndexRoute =
  AuthenticatedContentPagesIndexRouteImport.update({
    id: '/content/pages/',
    path: '/content/pages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductsIndexRoute =
  AuthenticatedCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductCommentsIndexRoute =
  AuthenticatedCatalogProductCommentsIndexRouteImport.update({
    id: '/catalog/product-comments/',
    path: '/catalog/product-comments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogOptionsIndexRoute =
  AuthenticatedCatalogOptionsIndexRouteImport.update({
    id: '/catalog/options/',
    path: '/catalog/options/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogCategoriesIndexRoute =
  AuthenticatedCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogAttributesIndexRoute =
  AuthenticatedCatalogAttributesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCatalogAttributesRouteRoute,
  } as any)
const AuthenticatedContentPagesCreateRoute =
  AuthenticatedContentPagesCreateRouteImport.update({
    id: '/content/pages/create',
    path: '/content/pages/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductsCreateRoute =
  AuthenticatedCatalogProductsCreateRouteImport.update({
    id: '/catalog/products/create',
    path: '/catalog/products/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogAttributesTemplatesRoute =
  AuthenticatedCatalogAttributesTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedCatalogAttributesRouteRoute,
  } as any)
const AuthenticatedCatalogAttributesGroupsRoute =
  AuthenticatedCatalogAttributesGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedCatalogAttributesRouteRoute,
  } as any)
const AuthenticatedCatalogOptionValuesIdIndexRoute =
  AuthenticatedCatalogOptionValuesIdIndexRouteImport.update({
    id: '/catalog/option-values/$id/',
    path: '/catalog/option-values/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderOrdersIdShowRoute =
  AuthenticatedOrderOrdersIdShowRouteImport.update({
    id: '/order/orders/$id/show',
    path: '/order/orders/$id/show',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentPagesIdEditRoute =
  AuthenticatedContentPagesIdEditRouteImport.update({
    id: '/content/pages/$id/edit',
    path: '/content/pages/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogProductsIdEditRoute =
  AuthenticatedCatalogProductsIdEditRouteImport.update({
    id: '/catalog/products/$id/edit',
    path: '/catalog/products/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogAttributesValuesIdIndexRoute =
  AuthenticatedCatalogAttributesValuesIdIndexRouteImport.update({
    id: '/values/$id/',
    path: '/values/$id/',
    getParentRoute: () => AuthenticatedCatalogAttributesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/catalog/attributes': typeof AuthenticatedCatalogAttributesRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/media': typeof AuthenticatedMediaIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/catalog/attributes/groups': typeof AuthenticatedCatalogAttributesGroupsRoute
  '/catalog/attributes/templates': typeof AuthenticatedCatalogAttributesTemplatesRoute
  '/catalog/products/create': typeof AuthenticatedCatalogProductsCreateRoute
  '/content/pages/create': typeof AuthenticatedContentPagesCreateRoute
  '/catalog/attributes/': typeof AuthenticatedCatalogAttributesIndexRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/catalog/options': typeof AuthenticatedCatalogOptionsIndexRoute
  '/catalog/product-comments': typeof AuthenticatedCatalogProductCommentsIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/content/pages': typeof AuthenticatedContentPagesIndexRoute
  '/order/orders': typeof AuthenticatedOrderOrdersIndexRoute
  '/setting/settings': typeof AuthenticatedSettingSettingsIndexRoute
  '/shipping/methods': typeof AuthenticatedShippingMethodsIndexRoute
  '/shipping/rates': typeof AuthenticatedShippingRatesIndexRoute
  '/shipping/shipments': typeof AuthenticatedShippingShipmentsIndexRoute
  '/shipping/zones': typeof AuthenticatedShippingZonesIndexRoute
  '/user/users': typeof AuthenticatedUserUsersIndexRoute
  '/catalog/products/$id/edit': typeof AuthenticatedCatalogProductsIdEditRoute
  '/content/pages/$id/edit': typeof AuthenticatedContentPagesIdEditRoute
  '/order/orders/$id/show': typeof AuthenticatedOrderOrdersIdShowRoute
  '/catalog/option-values/$id': typeof AuthenticatedCatalogOptionValuesIdIndexRoute
  '/catalog/attributes/values/$id': typeof AuthenticatedCatalogAttributesValuesIdIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/media': typeof AuthenticatedMediaIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/catalog/attributes/groups': typeof AuthenticatedCatalogAttributesGroupsRoute
  '/catalog/attributes/templates': typeof AuthenticatedCatalogAttributesTemplatesRoute
  '/catalog/products/create': typeof AuthenticatedCatalogProductsCreateRoute
  '/content/pages/create': typeof AuthenticatedContentPagesCreateRoute
  '/catalog/attributes': typeof AuthenticatedCatalogAttributesIndexRoute
  '/catalog/categories': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/catalog/options': typeof AuthenticatedCatalogOptionsIndexRoute
  '/catalog/product-comments': typeof AuthenticatedCatalogProductCommentsIndexRoute
  '/catalog/products': typeof AuthenticatedCatalogProductsIndexRoute
  '/content/pages': typeof AuthenticatedContentPagesIndexRoute
  '/order/orders': typeof AuthenticatedOrderOrdersIndexRoute
  '/setting/settings': typeof AuthenticatedSettingSettingsIndexRoute
  '/shipping/methods': typeof AuthenticatedShippingMethodsIndexRoute
  '/shipping/rates': typeof AuthenticatedShippingRatesIndexRoute
  '/shipping/shipments': typeof AuthenticatedShippingShipmentsIndexRoute
  '/shipping/zones': typeof AuthenticatedShippingZonesIndexRoute
  '/user/users': typeof AuthenticatedUserUsersIndexRoute
  '/catalog/products/$id/edit': typeof AuthenticatedCatalogProductsIdEditRoute
  '/content/pages/$id/edit': typeof AuthenticatedContentPagesIdEditRoute
  '/order/orders/$id/show': typeof AuthenticatedOrderOrdersIdShowRoute
  '/catalog/option-values/$id': typeof AuthenticatedCatalogOptionValuesIdIndexRoute
  '/catalog/attributes/values/$id': typeof AuthenticatedCatalogAttributesValuesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/catalog/attributes': typeof AuthenticatedCatalogAttributesRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/media/': typeof AuthenticatedMediaIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/catalog/attributes/groups': typeof AuthenticatedCatalogAttributesGroupsRoute
  '/_authenticated/catalog/attributes/templates': typeof AuthenticatedCatalogAttributesTemplatesRoute
  '/_authenticated/catalog/products/create': typeof AuthenticatedCatalogProductsCreateRoute
  '/_authenticated/content/pages/create': typeof AuthenticatedContentPagesCreateRoute
  '/_authenticated/catalog/attributes/': typeof AuthenticatedCatalogAttributesIndexRoute
  '/_authenticated/catalog/categories/': typeof AuthenticatedCatalogCategoriesIndexRoute
  '/_authenticated/catalog/options/': typeof AuthenticatedCatalogOptionsIndexRoute
  '/_authenticated/catalog/product-comments/': typeof AuthenticatedCatalogProductCommentsIndexRoute
  '/_authenticated/catalog/products/': typeof AuthenticatedCatalogProductsIndexRoute
  '/_authenticated/content/pages/': typeof AuthenticatedContentPagesIndexRoute
  '/_authenticated/order/orders/': typeof AuthenticatedOrderOrdersIndexRoute
  '/_authenticated/setting/settings/': typeof AuthenticatedSettingSettingsIndexRoute
  '/_authenticated/shipping/methods/': typeof AuthenticatedShippingMethodsIndexRoute
  '/_authenticated/shipping/rates/': typeof AuthenticatedShippingRatesIndexRoute
  '/_authenticated/shipping/shipments/': typeof AuthenticatedShippingShipmentsIndexRoute
  '/_authenticated/shipping/zones/': typeof AuthenticatedShippingZonesIndexRoute
  '/_authenticated/user/users/': typeof AuthenticatedUserUsersIndexRoute
  '/_authenticated/catalog/products/$id/edit': typeof AuthenticatedCatalogProductsIdEditRoute
  '/_authenticated/content/pages/$id/edit': typeof AuthenticatedContentPagesIdEditRoute
  '/_authenticated/order/orders/$id/show': typeof AuthenticatedOrderOrdersIdShowRoute
  '/_authenticated/catalog/option-values/$id/': typeof AuthenticatedCatalogOptionValuesIdIndexRoute
  '/_authenticated/catalog/attributes/values/$id/': typeof AuthenticatedCatalogAttributesValuesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/catalog/attributes'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/media'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/catalog/attributes/groups'
    | '/catalog/attributes/templates'
    | '/catalog/products/create'
    | '/content/pages/create'
    | '/catalog/attributes/'
    | '/catalog/categories'
    | '/catalog/options'
    | '/catalog/product-comments'
    | '/catalog/products'
    | '/content/pages'
    | '/order/orders'
    | '/setting/settings'
    | '/shipping/methods'
    | '/shipping/rates'
    | '/shipping/shipments'
    | '/shipping/zones'
    | '/user/users'
    | '/catalog/products/$id/edit'
    | '/content/pages/$id/edit'
    | '/order/orders/$id/show'
    | '/catalog/option-values/$id'
    | '/catalog/attributes/values/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/media'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/catalog/attributes/groups'
    | '/catalog/attributes/templates'
    | '/catalog/products/create'
    | '/content/pages/create'
    | '/catalog/attributes'
    | '/catalog/categories'
    | '/catalog/options'
    | '/catalog/product-comments'
    | '/catalog/products'
    | '/content/pages'
    | '/order/orders'
    | '/setting/settings'
    | '/shipping/methods'
    | '/shipping/rates'
    | '/shipping/shipments'
    | '/shipping/zones'
    | '/user/users'
    | '/catalog/products/$id/edit'
    | '/content/pages/$id/edit'
    | '/order/orders/$id/show'
    | '/catalog/option-values/$id'
    | '/catalog/attributes/values/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/catalog/attributes'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/media/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/catalog/attributes/groups'
    | '/_authenticated/catalog/attributes/templates'
    | '/_authenticated/catalog/products/create'
    | '/_authenticated/content/pages/create'
    | '/_authenticated/catalog/attributes/'
    | '/_authenticated/catalog/categories/'
    | '/_authenticated/catalog/options/'
    | '/_authenticated/catalog/product-comments/'
    | '/_authenticated/catalog/products/'
    | '/_authenticated/content/pages/'
    | '/_authenticated/order/orders/'
    | '/_authenticated/setting/settings/'
    | '/_authenticated/shipping/methods/'
    | '/_authenticated/shipping/rates/'
    | '/_authenticated/shipping/shipments/'
    | '/_authenticated/shipping/zones/'
    | '/_authenticated/user/users/'
    | '/_authenticated/catalog/products/$id/edit'
    | '/_authenticated/content/pages/$id/edit'
    | '/_authenticated/order/orders/$id/show'
    | '/_authenticated/catalog/option-values/$id/'
    | '/_authenticated/catalog/attributes/values/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/media/': {
      id: '/_authenticated/media/'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/attributes': {
      id: '/_authenticated/catalog/attributes'
      path: '/catalog/attributes'
      fullPath: '/catalog/attributes'
      preLoaderRoute: typeof AuthenticatedCatalogAttributesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/users/': {
      id: '/_authenticated/user/users/'
      path: '/user/users'
      fullPath: '/user/users'
      preLoaderRoute: typeof AuthenticatedUserUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipping/zones/': {
      id: '/_authenticated/shipping/zones/'
      path: '/shipping/zones'
      fullPath: '/shipping/zones'
      preLoaderRoute: typeof AuthenticatedShippingZonesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipping/shipments/': {
      id: '/_authenticated/shipping/shipments/'
      path: '/shipping/shipments'
      fullPath: '/shipping/shipments'
      preLoaderRoute: typeof AuthenticatedShippingShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipping/rates/': {
      id: '/_authenticated/shipping/rates/'
      path: '/shipping/rates'
      fullPath: '/shipping/rates'
      preLoaderRoute: typeof AuthenticatedShippingRatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipping/methods/': {
      id: '/_authenticated/shipping/methods/'
      path: '/shipping/methods'
      fullPath: '/shipping/methods'
      preLoaderRoute: typeof AuthenticatedShippingMethodsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setting/settings/': {
      id: '/_authenticated/setting/settings/'
      path: '/setting/settings'
      fullPath: '/setting/settings'
      preLoaderRoute: typeof AuthenticatedSettingSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order/orders/': {
      id: '/_authenticated/order/orders/'
      path: '/order/orders'
      fullPath: '/order/orders'
      preLoaderRoute: typeof AuthenticatedOrderOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/pages/': {
      id: '/_authenticated/content/pages/'
      path: '/content/pages'
      fullPath: '/content/pages'
      preLoaderRoute: typeof AuthenticatedContentPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/products/': {
      id: '/_authenticated/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof AuthenticatedCatalogProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/product-comments/': {
      id: '/_authenticated/catalog/product-comments/'
      path: '/catalog/product-comments'
      fullPath: '/catalog/product-comments'
      preLoaderRoute: typeof AuthenticatedCatalogProductCommentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/options/': {
      id: '/_authenticated/catalog/options/'
      path: '/catalog/options'
      fullPath: '/catalog/options'
      preLoaderRoute: typeof AuthenticatedCatalogOptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/categories/': {
      id: '/_authenticated/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/catalog/categories'
      preLoaderRoute: typeof AuthenticatedCatalogCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/attributes/': {
      id: '/_authenticated/catalog/attributes/'
      path: '/'
      fullPath: '/catalog/attributes/'
      preLoaderRoute: typeof AuthenticatedCatalogAttributesIndexRouteImport
      parentRoute: typeof AuthenticatedCatalogAttributesRouteRoute
    }
    '/_authenticated/content/pages/create': {
      id: '/_authenticated/content/pages/create'
      path: '/content/pages/create'
      fullPath: '/content/pages/create'
      preLoaderRoute: typeof AuthenticatedContentPagesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/products/create': {
      id: '/_authenticated/catalog/products/create'
      path: '/catalog/products/create'
      fullPath: '/catalog/products/create'
      preLoaderRoute: typeof AuthenticatedCatalogProductsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/attributes/templates': {
      id: '/_authenticated/catalog/attributes/templates'
      path: '/templates'
      fullPath: '/catalog/attributes/templates'
      preLoaderRoute: typeof AuthenticatedCatalogAttributesTemplatesRouteImport
      parentRoute: typeof AuthenticatedCatalogAttributesRouteRoute
    }
    '/_authenticated/catalog/attributes/groups': {
      id: '/_authenticated/catalog/attributes/groups'
      path: '/groups'
      fullPath: '/catalog/attributes/groups'
      preLoaderRoute: typeof AuthenticatedCatalogAttributesGroupsRouteImport
      parentRoute: typeof AuthenticatedCatalogAttributesRouteRoute
    }
    '/_authenticated/catalog/option-values/$id/': {
      id: '/_authenticated/catalog/option-values/$id/'
      path: '/catalog/option-values/$id'
      fullPath: '/catalog/option-values/$id'
      preLoaderRoute: typeof AuthenticatedCatalogOptionValuesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order/orders/$id/show': {
      id: '/_authenticated/order/orders/$id/show'
      path: '/order/orders/$id/show'
      fullPath: '/order/orders/$id/show'
      preLoaderRoute: typeof AuthenticatedOrderOrdersIdShowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/pages/$id/edit': {
      id: '/_authenticated/content/pages/$id/edit'
      path: '/content/pages/$id/edit'
      fullPath: '/content/pages/$id/edit'
      preLoaderRoute: typeof AuthenticatedContentPagesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/products/$id/edit': {
      id: '/_authenticated/catalog/products/$id/edit'
      path: '/catalog/products/$id/edit'
      fullPath: '/catalog/products/$id/edit'
      preLoaderRoute: typeof AuthenticatedCatalogProductsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/attributes/values/$id/': {
      id: '/_authenticated/catalog/attributes/values/$id/'
      path: '/values/$id'
      fullPath: '/catalog/attributes/values/$id'
      preLoaderRoute: typeof AuthenticatedCatalogAttributesValuesIdIndexRouteImport
      parentRoute: typeof AuthenticatedCatalogAttributesRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedCatalogAttributesRouteRouteChildren {
  AuthenticatedCatalogAttributesGroupsRoute: typeof AuthenticatedCatalogAttributesGroupsRoute
  AuthenticatedCatalogAttributesTemplatesRoute: typeof AuthenticatedCatalogAttributesTemplatesRoute
  AuthenticatedCatalogAttributesIndexRoute: typeof AuthenticatedCatalogAttributesIndexRoute
  AuthenticatedCatalogAttributesValuesIdIndexRoute: typeof AuthenticatedCatalogAttributesValuesIdIndexRoute
}

const AuthenticatedCatalogAttributesRouteRouteChildren: AuthenticatedCatalogAttributesRouteRouteChildren =
  {
    AuthenticatedCatalogAttributesGroupsRoute:
      AuthenticatedCatalogAttributesGroupsRoute,
    AuthenticatedCatalogAttributesTemplatesRoute:
      AuthenticatedCatalogAttributesTemplatesRoute,
    AuthenticatedCatalogAttributesIndexRoute:
      AuthenticatedCatalogAttributesIndexRoute,
    AuthenticatedCatalogAttributesValuesIdIndexRoute:
      AuthenticatedCatalogAttributesValuesIdIndexRoute,
  }

const AuthenticatedCatalogAttributesRouteRouteWithChildren =
  AuthenticatedCatalogAttributesRouteRoute._addFileChildren(
    AuthenticatedCatalogAttributesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatalogAttributesRouteRoute: typeof AuthenticatedCatalogAttributesRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMediaIndexRoute: typeof AuthenticatedMediaIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedCatalogProductsCreateRoute: typeof AuthenticatedCatalogProductsCreateRoute
  AuthenticatedContentPagesCreateRoute: typeof AuthenticatedContentPagesCreateRoute
  AuthenticatedCatalogCategoriesIndexRoute: typeof AuthenticatedCatalogCategoriesIndexRoute
  AuthenticatedCatalogOptionsIndexRoute: typeof AuthenticatedCatalogOptionsIndexRoute
  AuthenticatedCatalogProductCommentsIndexRoute: typeof AuthenticatedCatalogProductCommentsIndexRoute
  AuthenticatedCatalogProductsIndexRoute: typeof AuthenticatedCatalogProductsIndexRoute
  AuthenticatedContentPagesIndexRoute: typeof AuthenticatedContentPagesIndexRoute
  AuthenticatedOrderOrdersIndexRoute: typeof AuthenticatedOrderOrdersIndexRoute
  AuthenticatedSettingSettingsIndexRoute: typeof AuthenticatedSettingSettingsIndexRoute
  AuthenticatedShippingMethodsIndexRoute: typeof AuthenticatedShippingMethodsIndexRoute
  AuthenticatedShippingRatesIndexRoute: typeof AuthenticatedShippingRatesIndexRoute
  AuthenticatedShippingShipmentsIndexRoute: typeof AuthenticatedShippingShipmentsIndexRoute
  AuthenticatedShippingZonesIndexRoute: typeof AuthenticatedShippingZonesIndexRoute
  AuthenticatedUserUsersIndexRoute: typeof AuthenticatedUserUsersIndexRoute
  AuthenticatedCatalogProductsIdEditRoute: typeof AuthenticatedCatalogProductsIdEditRoute
  AuthenticatedContentPagesIdEditRoute: typeof AuthenticatedContentPagesIdEditRoute
  AuthenticatedOrderOrdersIdShowRoute: typeof AuthenticatedOrderOrdersIdShowRoute
  AuthenticatedCatalogOptionValuesIdIndexRoute: typeof AuthenticatedCatalogOptionValuesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatalogAttributesRouteRoute:
    AuthenticatedCatalogAttributesRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMediaIndexRoute: AuthenticatedMediaIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedCatalogProductsCreateRoute:
    AuthenticatedCatalogProductsCreateRoute,
  AuthenticatedContentPagesCreateRoute: AuthenticatedContentPagesCreateRoute,
  AuthenticatedCatalogCategoriesIndexRoute:
    AuthenticatedCatalogCategoriesIndexRoute,
  AuthenticatedCatalogOptionsIndexRoute: AuthenticatedCatalogOptionsIndexRoute,
  AuthenticatedCatalogProductCommentsIndexRoute:
    AuthenticatedCatalogProductCommentsIndexRoute,
  AuthenticatedCatalogProductsIndexRoute:
    AuthenticatedCatalogProductsIndexRoute,
  AuthenticatedContentPagesIndexRoute: AuthenticatedContentPagesIndexRoute,
  AuthenticatedOrderOrdersIndexRoute: AuthenticatedOrderOrdersIndexRoute,
  AuthenticatedSettingSettingsIndexRoute:
    AuthenticatedSettingSettingsIndexRoute,
  AuthenticatedShippingMethodsIndexRoute:
    AuthenticatedShippingMethodsIndexRoute,
  AuthenticatedShippingRatesIndexRoute: AuthenticatedShippingRatesIndexRoute,
  AuthenticatedShippingShipmentsIndexRoute:
    AuthenticatedShippingShipmentsIndexRoute,
  AuthenticatedShippingZonesIndexRoute: AuthenticatedShippingZonesIndexRoute,
  AuthenticatedUserUsersIndexRoute: AuthenticatedUserUsersIndexRoute,
  AuthenticatedCatalogProductsIdEditRoute:
    AuthenticatedCatalogProductsIdEditRoute,
  AuthenticatedContentPagesIdEditRoute: AuthenticatedContentPagesIdEditRoute,
  AuthenticatedOrderOrdersIdShowRoute: AuthenticatedOrderOrdersIdShowRoute,
  AuthenticatedCatalogOptionValuesIdIndexRoute:
    AuthenticatedCatalogOptionValuesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
